/**
 * WidgetCraft - Clock Widget Templates
 * M3 Expressive clock designs with dynamic colors
 *
 * COORDINATE SYSTEM: All components use top-left positioning.
 * (x, y) = top-left corner of the component bounding box.
 * Widget sizes: small=180×90, medium=180×180, large=360×180, extraLarge=360×360
 */

import { WidgetTemplate } from '../types';

// ============================================
// Digital Clock - Minimal (medium: 180×180)
// ============================================

export const digitalClockMinimal: WidgetTemplate = {
    id: 'clock-digital-minimal',
    name: 'Digital Minimal',
    description: 'Clean digital time display with date',
    category: 'time',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'primaryContainer',
            cornerRadius: 32,
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 4,
                blur: 12,
                opacity: 0.12,
            },
        },
        clock: {
            id: 'clock',
            type: 'digitalClock',
            x: 10,
            y: 50,
            width: 160,
            height: 60,
            format: '24h',
            showSeconds: false,
            fontSize: 52,
            fontWeight: 'bold',
            color: 'onPrimaryContainer',
            textAlign: 'center',
        },
        date: {
            id: 'date',
            type: 'text',
            x: 10,
            y: 118,
            width: 160,
            height: 24,
            content: '{date.dayShort}, {date.monthShort} {date.day}',
            fontSize: 15,
            fontWeight: 'medium',
            color: 'onPrimaryContainer',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'clock', 'date'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'primaryContainer',
        onBackground: 'onPrimaryContainer',
    },
    dataBindings: ['time.formatted24', 'date.dayShort', 'date.monthShort', 'date.day'],
};

// ============================================
// Digital Clock - Artistic (large: 360×180)
// ============================================

export const digitalClockArtistic: WidgetTemplate = {
    id: 'clock-digital-artistic',
    name: 'Artistic Split',
    description: 'Bold artistic time with split numbers',
    category: 'time',
    size: 'large',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 180,
            shapeType: 'squircle',
            fill: 'surfaceVariant',
            cornerRadius: 32,
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 2,
                blur: 8,
                opacity: 0.08,
            },
        },
        hours: {
            id: 'hours',
            type: 'text',
            x: 20,
            y: 30,
            width: 120,
            height: 100,
            content: '{time.hours}',
            fontSize: 80,
            fontWeight: 'bold',
            color: 'primary',
            textAlign: 'center',
        },
        separator: {
            id: 'separator',
            type: 'text',
            x: 170,
            y: 40,
            width: 20,
            height: 60,
            content: ':',
            fontSize: 60,
            fontWeight: 'bold',
            color: 'tertiary',
            textAlign: 'center',
        },
        minutes: {
            id: 'minutes',
            type: 'text',
            x: 220,
            y: 30,
            width: 120,
            height: 100,
            content: '{time.minutes}',
            fontSize: 80,
            fontWeight: 'bold',
            color: 'secondary',
            textAlign: 'center',
        },
        dateLabel: {
            id: 'dateLabel',
            type: 'text',
            x: 80,
            y: 148,
            width: 200,
            height: 20,
            content: '{date.dayName}, {date.monthName} {date.day}',
            fontSize: 14,
            fontWeight: 'medium',
            color: 'onSurfaceVariant',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'hours', 'separator', 'minutes', 'dateLabel'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'surfaceVariant',
        onBackground: 'onSurfaceVariant',
    },
    dataBindings: ['time.hours', 'time.minutes', 'date.dayName', 'date.monthName', 'date.day'],
};

// ============================================
// Date Focus Widget (small: 180×90)
// ============================================

export const dateFocusWidget: WidgetTemplate = {
    id: 'date-focus',
    name: 'Date Focus',
    description: 'Large date display with day number',
    category: 'time',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 90,
            shapeType: 'squircle',
            fill: 'tertiaryContainer',
            cornerRadius: 24,
        },
        dayNum: {
            id: 'dayNum',
            type: 'text',
            x: 15,
            y: 15,
            width: 65,
            height: 60,
            content: '{date.day}',
            fontSize: 42,
            fontWeight: 'bold',
            color: 'onTertiaryContainer',
            textAlign: 'center',
        },
        monthYear: {
            id: 'monthYear',
            type: 'text',
            x: 90,
            y: 22,
            width: 80,
            height: 22,
            content: '{date.monthShort}',
            fontSize: 16,
            fontWeight: 'semibold',
            color: 'tertiary',
            textAlign: 'left',
        },
        dayName: {
            id: 'dayName',
            type: 'text',
            x: 90,
            y: 48,
            width: 80,
            height: 20,
            content: '{date.dayName}',
            fontSize: 12,
            fontWeight: 'normal',
            color: 'onTertiaryContainer',
            textAlign: 'left',
        },
    },
    componentOrder: ['bg', 'dayNum', 'monthYear', 'dayName'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onTertiaryContainer',
        accent: 'tertiary',
        background: 'tertiaryContainer',
        onBackground: 'onTertiaryContainer',
    },
    dataBindings: ['date.day', 'date.monthShort', 'date.dayName'],
};

// ============================================
// Analog Clock - Classic (medium: 180×180)
// ============================================

export const analogClockClassic: WidgetTemplate = {
    id: 'clock-analog-classic',
    name: 'Analog Classic',
    description: 'Classic analog clock with roman numerals',
    category: 'time',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'circle',
            fill: 'surface',
            cornerRadius: 90,
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 4,
                blur: 16,
                opacity: 0.15,
            },
        },
        face: {
            id: 'face',
            type: 'shape',
            x: 8,
            y: 8,
            width: 164,
            height: 164,
            shapeType: 'circle',
            fill: 'primaryContainer',
            cornerRadius: 82,
            stroke: 'primary',
            strokeWidth: 2,
        },
        clock: {
            id: 'clock',
            type: 'analogClock',
            x: 15,
            y: 15,
            width: 150,
            height: 150,
            faceStyle: 'roman',
            handStyle: 'classic',
            showSeconds: true,
            showNumbers: true,
            showTicks: true,
            smoothSeconds: true,
            faceColor: 'transparent',
            hourHandColor: 'onPrimaryContainer',
            minuteHandColor: 'onPrimaryContainer',
            secondHandColor: 'primary',
            tickColor: 'onPrimaryContainer',
            numberColor: 'onPrimaryContainer',
        },
    },
    componentOrder: ['bg', 'face', 'clock'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'onPrimaryContainer',
        accent: 'primary',
        background: 'primaryContainer',
        onBackground: 'onPrimaryContainer',
    },
    dataBindings: ['time.hours', 'time.minutes', 'time.seconds'],
};

// ============================================
// Analog Clock - Modern (medium: 180×180)
// ============================================

export const analogClockModern: WidgetTemplate = {
    id: 'clock-analog-modern',
    name: 'Analog Modern',
    description: 'Sleek modern analog with thin hands',
    category: 'time',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'inverseSurface',
            cornerRadius: 32,
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 6,
                blur: 20,
                opacity: 0.2,
            },
        },
        clock: {
            id: 'clock',
            type: 'analogClock',
            x: 15,
            y: 15,
            width: 150,
            height: 150,
            faceStyle: 'dots',
            handStyle: 'thin',
            showSeconds: true,
            showNumbers: false,
            showTicks: true,
            smoothSeconds: true,
            faceColor: 'transparent',
            hourHandColor: 'inverseOnSurface',
            minuteHandColor: 'inverseOnSurface',
            secondHandColor: 'inversePrimary',
            tickColor: 'outline',
            numberColor: 'inverseOnSurface',
        },
    },
    componentOrder: ['bg', 'clock'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'inverseSurface',
        onBackground: 'inverseOnSurface',
    },
    dataBindings: ['time.hours', 'time.minutes', 'time.seconds'],
};

// ============================================
// Fluid Gradient Clock (large: 360×180)
// ============================================

export const fluidGradientClock: WidgetTemplate = {
    id: 'clock-fluid-gradient',
    name: 'Fluid Gradient',
    description: 'Vibrant gradient background with elegant time',
    category: 'time',
    size: 'large',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 180,
            shapeType: 'squircle',
            fill: 'primary',
            cornerRadius: 32,
            gradient: {
                type: 'linear',
                colors: ['primary', 'secondary', 'tertiary'],
                angle: 135,
            },
            shadow: {
                color: 'primary',
                offsetX: 0,
                offsetY: 8,
                blur: 24,
                opacity: 0.3,
            },
        },
        clock: {
            id: 'clock',
            type: 'digitalClock',
            x: 24,
            y: 30,
            width: 200,
            height: 70,
            format: '24h',
            showSeconds: false,
            fontSize: 64,
            fontWeight: 'normal',
            color: 'onPrimary',
            textAlign: 'left',
        },
        date: {
            id: 'date',
            type: 'text',
            x: 24,
            y: 115,
            width: 200,
            height: 22,
            content: '{date.dayName}, {date.monthName} {date.day}',
            fontSize: 16,
            fontWeight: 'medium',
            color: 'onPrimary',
            textAlign: 'left',
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 1,
                blur: 3,
                opacity: 0.2,
            },
        },
        greeting: {
            id: 'greeting',
            type: 'text',
            x: 24,
            y: 142,
            width: 200,
            height: 18,
            content: '{device.greeting}',
            fontSize: 13,
            fontWeight: 'normal',
            color: 'onPrimary',
            textAlign: 'left',
            opacity: 0.7,
        },
    },
    componentOrder: ['bg', 'clock', 'date', 'greeting'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'primary',
        onBackground: 'onPrimary',
    },
    dataBindings: ['time.formatted24', 'date.dayName', 'date.monthName', 'date.day', 'device.greeting'],
};

// ============================================
// Analog Premium (extraLarge: 360×360)
// ============================================

export const analogPremium: WidgetTemplate = {
    id: 'clock-analog-premium',
    name: 'Analog Premium',
    description: 'Premium analog with arrow hands and gradient ring',
    category: 'time',
    size: 'extraLarge',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 360,
            shapeType: 'squircle',
            fill: 'inverseSurface',
            cornerRadius: 48,
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 8,
                blur: 32,
                opacity: 0.25,
            },
        },
        outerRing: {
            id: 'outerRing',
            type: 'shape',
            x: 20,
            y: 20,
            width: 320,
            height: 320,
            shapeType: 'circle',
            fill: 'transparent',
            cornerRadius: 160,
            stroke: 'outline',
            strokeWidth: 3,
        },
        innerRing: {
            id: 'innerRing',
            type: 'shape',
            x: 30,
            y: 30,
            width: 300,
            height: 300,
            shapeType: 'circle',
            fill: 'surfaceVariant',
            cornerRadius: 150,
            gradient: {
                type: 'radial',
                colors: ['surfaceVariant', 'inverseSurface'],
            },
        },
        clock: {
            id: 'clock',
            type: 'analogClock',
            x: 50,
            y: 50,
            width: 260,
            height: 260,
            faceStyle: 'lines',
            handStyle: 'arrow',
            showSeconds: true,
            showNumbers: true,
            showTicks: true,
            smoothSeconds: true,
            faceColor: 'transparent',
            hourHandColor: 'inverseOnSurface',
            minuteHandColor: 'inversePrimary',
            secondHandColor: 'tertiary',
            tickColor: 'outline',
            numberColor: 'onSurfaceVariant',
        },
        dateChip: {
            id: 'dateChip',
            type: 'shape',
            x: 135,
            y: 318,
            width: 90,
            height: 28,
            shapeType: 'pill',
            fill: 'surfaceVariant',
            cornerRadius: 14,
        },
        dateText: {
            id: 'dateText',
            type: 'text',
            x: 140,
            y: 322,
            width: 80,
            height: 20,
            content: '{date.dayShort} {date.day}',
            fontSize: 11,
            fontWeight: 'medium',
            color: 'onSurfaceVariant',
            textAlign: 'center',
            letterSpacing: 0.5,
        },
    },
    componentOrder: ['bg', 'outerRing', 'innerRing', 'clock', 'dateChip', 'dateText'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'inverseSurface',
        onBackground: 'inverseOnSurface',
    },
    dataBindings: ['time.hours', 'time.minutes', 'time.seconds', 'date.dayShort', 'date.day'],
};

// ============================================
// Retro Digital Clock (large: 360×180)
// ============================================

export const retroDigitalClock: WidgetTemplate = {
    id: 'clock-retro-digital',
    name: 'Retro Digital',
    description: 'High-contrast retro LED style clock',
    category: 'time',
    size: 'large',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 180,
            shapeType: 'rectangle',
            fill: '#0A0A0A',
            cornerRadius: 16,
            shadow: {
                color: 'rgba(0,255,65,0.08)',
                offsetX: 0,
                offsetY: 0,
                blur: 20,
                opacity: 0.08,
            },
        },
        scanline: {
            id: 'scanline',
            type: 'shape',
            x: 8,
            y: 8,
            width: 344,
            height: 164,
            shapeType: 'rectangle',
            fill: '#111111',
            cornerRadius: 8,
            stroke: '#1A1A1A',
            strokeWidth: 1,
        },
        clock: {
            id: 'clock',
            type: 'digitalClock',
            x: 20,
            y: 30,
            width: 320,
            height: 80,
            format: '24h',
            showSeconds: true,
            fontSize: 72,
            fontWeight: 'bold',
            fontFamily: 'monospace',
            color: '#00FF41',
            textAlign: 'center',
        },
        dateRow: {
            id: 'dateRow',
            type: 'text',
            x: 40,
            y: 130,
            width: 280,
            height: 18,
            content: '{date.dayName}  {date.year}-{date.month}-{date.day}',
            fontSize: 14,
            fontWeight: 'normal',
            fontFamily: 'monospace',
            color: '#00FF41',
            textAlign: 'center',
            letterSpacing: 2,
        },
        dot1: {
            id: 'dot1',
            type: 'shape',
            x: 16,
            y: 16,
            width: 6,
            height: 6,
            shapeType: 'circle',
            fill: '#00FF41',
            cornerRadius: 3,
        },
        dot2: {
            id: 'dot2',
            type: 'shape',
            x: 338,
            y: 16,
            width: 6,
            height: 6,
            shapeType: 'circle',
            fill: '#FF3333',
            cornerRadius: 3,
        },
    },
    componentOrder: ['bg', 'scanline', 'dot1', 'dot2', 'clock', 'dateRow'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: '#00FF41',
        secondary: '#00CC33',
        accent: '#FF3333',
        background: '#0A0A0A',
        onBackground: '#00FF41',
    },
    dataBindings: ['time.formatted24', 'time.seconds', 'date.dayName', 'date.year', 'date.month', 'date.day'],
};

// ============================================
// Glassmorphism Time (medium: 180×180)
// ============================================

export const glassmorphismClock: WidgetTemplate = {
    id: 'clock-glassmorphism',
    name: 'Glass Time',
    description: 'Frosted glass effect with elegant typography',
    category: 'time',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'surface',
            cornerRadius: 32,
            blur: 20,
            stroke: 'outline',
            strokeWidth: 1,
            opacity: 0.15,
            shadow: {
                color: 'onSurface',
                offsetX: 0,
                offsetY: 4,
                blur: 16,
                opacity: 0.15,
            },
        },
        accentBar: {
            id: 'accentBar',
            type: 'shape',
            x: 24,
            y: 30,
            width: 3,
            height: 40,
            shapeType: 'pill',
            fill: 'primary',
            cornerRadius: 2,
        },
        clock: {
            id: 'clock',
            type: 'digitalClock',
            x: 36,
            y: 28,
            width: 130,
            height: 50,
            format: '12h',
            showSeconds: false,
            showAmPm: true,
            fontSize: 42,
            fontWeight: 'bold',
            color: 'onSurface',
            textAlign: 'left',
        },
        divider: {
            id: 'divider',
            type: 'shape',
            x: 24,
            y: 95,
            width: 132,
            height: 1,
            shapeType: 'rectangle',
            fill: 'outline',
            cornerRadius: 0,
        },
        date: {
            id: 'date',
            type: 'text',
            x: 24,
            y: 108,
            width: 140,
            height: 18,
            content: '{date.dayName}',
            fontSize: 15,
            fontWeight: 'medium',
            color: 'onSurface',
            textAlign: 'left',
            letterSpacing: 1,
        },
        dateNum: {
            id: 'dateNum',
            type: 'text',
            x: 24,
            y: 132,
            width: 140,
            height: 16,
            content: '{date.monthName} {date.day}, {date.year}',
            fontSize: 12,
            fontWeight: 'normal',
            color: 'onSurfaceVariant',
            textAlign: 'left',
        },
    },
    componentOrder: ['bg', 'accentBar', 'clock', 'divider', 'date', 'dateNum'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'onSurface',
        accent: 'primary',
        background: 'surface',
        onBackground: 'onSurface',
    },
    dataBindings: ['time.formatted12', 'time.ampm', 'date.dayName', 'date.monthName', 'date.day', 'date.year'],
};

// Export all clock templates
export const clockTemplates = [
    digitalClockMinimal,
    digitalClockArtistic,
    dateFocusWidget,
    analogClockClassic,
    analogClockModern,
    fluidGradientClock,
    analogPremium,
    retroDigitalClock,
    glassmorphismClock,
];
