/**
 * WidgetCraft - Media Widget Templates
 * Music player and media control widgets
 *
 * COORDINATE SYSTEM: All components use top-left positioning.
 * (x, y) = top-left corner of the component bounding box.
 * Widget sizes: small=180×90, medium=180×180, large=360×180, extraLarge=360×360
 */

import { WidgetTemplate } from '../types';

// ============================================
// Music Player - Compact (small: 180×90)
// ============================================

export const musicCompact: WidgetTemplate = {
    id: 'music-compact',
    name: 'Music Compact',
    description: 'Minimal now playing display',
    category: 'media',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 90,
            shapeType: 'squircle',
            fill: 'tertiaryContainer',
            cornerRadius: 24,
        },
        albumArt: {
            id: 'albumArt',
            type: 'shape',
            x: 15,
            y: 15,
            width: 60,
            height: 60,
            shapeType: 'squircle',
            fill: 'tertiary',
            cornerRadius: 16,
        },
        playIcon: {
            id: 'playIcon',
            type: 'icon',
            x: 35,
            y: 35,
            width: 20,
            height: 20,
            name: 'play',
            color: 'onTertiary',
            size: 20,
        },
        title: {
            id: 'title',
            type: 'text',
            x: 85,
            y: 25,
            width: 85,
            height: 20,
            content: '{music.title}',
            fontSize: 14,
            fontWeight: 'bold',
            color: 'onTertiaryContainer',
            textAlign: 'left',
            letterSpacing: 0.2,
        },
        artist: {
            id: 'artist',
            type: 'text',
            x: 85,
            y: 48,
            width: 85,
            height: 16,
            content: '{music.artist}',
            fontSize: 12,
            fontWeight: 'medium',
            color: 'onTertiaryContainer',
            textAlign: 'left',
            opacity: 0.7,
        },
    },
    componentOrder: ['bg', 'albumArt', 'playIcon', 'title', 'artist'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onTertiaryContainer',
        accent: 'tertiary',
        background: 'tertiaryContainer',
        onBackground: 'onTertiaryContainer',
    },
    dataBindings: ['music.title', 'music.artist', 'music.isPlaying'],
};

// ============================================
// Music Player - Full (large: 360×180)
// ============================================

export const musicFull: WidgetTemplate = {
    id: 'music-full',
    name: 'Music Full',
    description: 'Complete music player controls',
    category: 'media',
    size: 'large',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 180,
            shapeType: 'squircle',
            fill: 'surfaceVariant',
            cornerRadius: 32,
        },
        albumArt: {
            id: 'albumArt',
            type: 'shape',
            x: 20,
            y: 20,
            width: 140,
            height: 140,
            shapeType: 'squircle',
            fill: 'tertiary',
            cornerRadius: 24,
        },
        albumIcon: {
            id: 'albumIcon',
            type: 'icon',
            x: 65,
            y: 65,
            width: 50,
            height: 50,
            name: 'music',
            color: 'onTertiary',
            size: 50,
        },
        title: {
            id: 'title',
            type: 'text',
            x: 175,
            y: 30,
            width: 170,
            height: 24,
            content: 'No Music Playing',
            fontSize: 16,
            fontWeight: 'bold',
            color: 'onSurfaceVariant',
            textAlign: 'left',
            letterSpacing: 0.3,
        },
        artist: {
            id: 'artist',
            type: 'text',
            x: 175,
            y: 56,
            width: 170,
            height: 18,
            content: 'Tap to Play',
            fontSize: 14,
            fontWeight: 'medium',
            color: 'onSurfaceVariant',
            textAlign: 'left',
            opacity: 0.7,
        },
        // Progress bar
        progressBg: {
            id: 'progressBg',
            type: 'shape',
            x: 180,
            y: 95,
            width: 160,
            height: 6,
            shapeType: 'pill',
            fill: 'onSurfaceVariant',
            fillOpacity: 0.1,
            cornerRadius: 3,
        },
        progress: {
            id: 'progress',
            type: 'shape',
            x: 180,
            y: 95,
            width: 80,
            height: 6,
            shapeType: 'pill',
            fill: 'tertiary',
            cornerRadius: 3,
        },
        timeStart: {
            id: 'timeStart',
            type: 'text',
            x: 180,
            y: 106,
            width: 40,
            height: 14,
            content: '2:05',
            fontSize: 10,
            fontWeight: 'medium',
            color: 'onSurfaceVariant',
            textAlign: 'left',
            opacity: 0.6,
        },
        timeEnd: {
            id: 'timeEnd',
            type: 'text',
            x: 300,
            y: 106,
            width: 40,
            height: 14,
            content: '3:24',
            fontSize: 10,
            fontWeight: 'medium',
            color: 'onSurfaceVariant',
            textAlign: 'right',
            opacity: 0.6,
        },
        // Controls
        prevBtn: {
            id: 'prevBtn',
            type: 'icon',
            x: 200,
            y: 135,
            width: 24,
            height: 24,
            name: 'skip-previous',
            color: 'onSurfaceVariant',
            size: 24,
        },
        playBtn: {
            id: 'playBtn',
            type: 'icon',
            x: 248,
            y: 130,
            width: 32,
            height: 32,
            name: 'play-circle',
            color: 'tertiary',
            size: 32,
        },
        nextBtn: {
            id: 'nextBtn',
            type: 'icon',
            x: 300,
            y: 135,
            width: 24,
            height: 24,
            name: 'skip-next',
            color: 'onSurfaceVariant',
            size: 24,
        },
    },
    componentOrder: [
        'bg', 'albumArt', 'albumIcon', 'title', 'artist',
        'progressBg', 'progress', 'timeStart', 'timeEnd',
        'prevBtn', 'playBtn', 'nextBtn',
    ],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onSurfaceVariant',
        accent: 'tertiary',
        background: 'surfaceVariant',
        onBackground: 'onSurfaceVariant',
    },
    dataBindings: ['music.title', 'music.artist', 'music.isPlaying'],
};

// ============================================
// Now Playing (medium: 180×180)
// ============================================

export const nowPlaying: WidgetTemplate = {
    id: 'now-playing',
    name: 'Now Playing',
    description: 'Immersive album art display',
    category: 'media',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'tertiary',
            cornerRadius: 32,
        },
        artPlaceholder: {
            id: 'artPlaceholder',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'tertiary',
            cornerRadius: 32,
            gradient: {
                type: 'linear',
                colors: ['transparent', 'onTertiary'],
                angle: 180,
            },
            opacity: 0.75,
        },
        icon: {
            id: 'icon',
            type: 'icon',
            x: 70,
            y: 40,
            width: 40,
            height: 40,
            name: 'music-note',
            color: 'onTertiary',
            size: 40,
            opacity: 0.5,
        },
        title: {
            id: 'title',
            type: 'text',
            x: 5,
            y: 100,
            width: 170,
            height: 24,
            content: 'Bohemian Rhapsody',
            fontSize: 14,
            fontWeight: 'bold',
            color: 'onTertiary',
            textAlign: 'center',
        },
        artist: {
            id: 'artist',
            type: 'text',
            x: 5,
            y: 126,
            width: 170,
            height: 18,
            content: 'Queen',
            fontSize: 13,
            fontWeight: 'medium',
            color: 'onTertiary',
            opacity: 0.8,
            textAlign: 'center',
        },
        progress: {
            id: 'progress',
            type: 'shape',
            x: 40,
            y: 158,
            width: 100,
            height: 4,
            shapeType: 'pill',
            fill: 'onTertiary',
            cornerRadius: 2,
            opacity: 0.8,
        },
    },
    componentOrder: ['bg', 'artPlaceholder', 'icon', 'title', 'artist', 'progress'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onTertiary',
        accent: 'tertiary',
        background: 'tertiary',
        onBackground: 'onTertiary',
    },
    dataBindings: ['music.title', 'music.artist'],
};

// ============================================
// Photo Frame (medium: 180×180)
// ============================================

export const photoFrame: WidgetTemplate = {
    id: 'photo-frame',
    name: 'Photo Frame',
    description: 'Polaroid style photo display',
    category: 'media',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 10,
            y: 5,
            width: 160,
            height: 170,
            shapeType: 'rectangle',
            fill: 'surface',
            cornerRadius: 4,
            shadow: {
                color: 'onSurface',
                offsetX: 2,
                offsetY: 4,
                blur: 6,
                opacity: 0.2,
            },
        },
        photoArea: {
            id: 'photoArea',
            type: 'shape',
            x: 22,
            y: 16,
            width: 136,
            height: 120,
            shapeType: 'rectangle',
            fill: 'surfaceVariant',
            cornerRadius: 2,
        },
        icon: {
            id: 'icon',
            type: 'icon',
            x: 74,
            y: 60,
            width: 32,
            height: 32,
            name: 'image',
            color: 'onSurfaceVariant',
            size: 32,
        },
        caption: {
            id: 'caption',
            type: 'text',
            x: 20,
            y: 148,
            width: 140,
            height: 20,
            content: 'Summer 2024',
            fontSize: 14,
            fontWeight: 'normal',
            color: 'onSurface',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'photoArea', 'icon', 'caption'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'surface',
        onBackground: 'onSurface',
    },
    dataBindings: [],
};

// Export all media templates
export const mediaTemplates = [
    musicCompact,
    musicFull,
    nowPlaying,
    photoFrame,
];

