/**
 * WidgetCraft - Quote & Text Widget Templates
 * Inspirational quotes and text displays
 *
 * COORDINATE SYSTEM: All components use top-left positioning.
 * (x, y) = top-left corner of the component bounding box.
 * Widget sizes: small=180×90, medium=180×180, large=360×180, extraLarge=360×360
 */

import { WidgetTemplate } from '../types';

// ============================================
// Quote Widget - Minimal (medium: 180×180)
// ============================================

export const quoteMinimal: WidgetTemplate = {
    id: 'quote-minimal',
    name: 'Quote Minimal',
    description: 'Simple inspirational quote',
    category: 'productivity',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'surfaceVariant',
            cornerRadius: 32,
        },
        quoteIcon: {
            id: 'quoteIcon',
            type: 'icon',
            x: 20,
            y: 20,
            width: 32,
            height: 32,
            name: 'format-quote-open',
            color: 'primary',
            size: 32,
        },
        quoteText: {
            id: 'quoteText',
            type: 'text',
            x: 15,
            y: 60,
            width: 150,
            height: 72,
            content: 'Whatever you are, be a good one.',
            fontSize: 16,
            fontWeight: 'medium',
            color: 'onSurfaceVariant',
            textAlign: 'center',
            lineHeight: 24,
        },
        author: {
            id: 'author',
            type: 'text',
            x: 15,
            y: 145,
            width: 150,
            height: 16,
            content: '— Abraham Lincoln',
            fontSize: 12,
            fontWeight: 'normal',
            color: 'primary',
            textAlign: 'center',
            opacity: 0.8,
        },
    },
    componentOrder: ['bg', 'quoteIcon', 'quoteText', 'author'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'onSurfaceVariant',
        accent: 'primary',
        background: 'surfaceVariant',
        onBackground: 'onSurfaceVariant',
    },
    dataBindings: [],
};

// ============================================
// Quote Widget - Bold (large: 360×180)
// ============================================

export const quoteBold: WidgetTemplate = {
    id: 'quote-bold',
    name: 'Quote Bold',
    description: 'Large bold typography quote',
    category: 'productivity',
    size: 'large',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 180,
            shapeType: 'squircle',
            fill: 'primaryContainer',
            cornerRadius: 32,
        },
        decorShape: {
            id: 'decorShape',
            type: 'shape',
            x: -20,
            y: -20,
            width: 140,
            height: 140,
            shapeType: 'circle',
            fill: 'primary',
            fillOpacity: 0.1,
        },
        quoteText: {
            id: 'quoteText',
            type: 'text',
            x: 30,
            y: 20,
            width: 300,
            height: 100,
            content: 'Dream big.\nStart small.\nAct now.',
            fontSize: 28,
            fontWeight: 'bold',
            color: 'onPrimaryContainer',
            textAlign: 'center',
            lineHeight: 34,
        },
        author: {
            id: 'author',
            type: 'text',
            x: 80,
            y: 135,
            width: 200,
            height: 20,
            content: '— Robin Sharma',
            fontSize: 14,
            fontWeight: 'medium',
            color: 'primary',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'decorShape', 'quoteText', 'author'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'onPrimaryContainer',
        accent: 'primary',
        background: 'primaryContainer',
        onBackground: 'onPrimaryContainer',
    },
    dataBindings: [],
};

// ============================================
// Curved Quote (medium: 180×180)
// ============================================

export const curvedQuote: WidgetTemplate = {
    id: 'curved-quote',
    name: 'Curved Quote',
    description: 'Circular text layout',
    category: 'productivity',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'circle',
            fill: 'tertiaryContainer',
        },
        ringOuter: {
            id: 'ringOuter',
            type: 'shape',
            x: 8,
            y: 8,
            width: 164,
            height: 164,
            shapeType: 'circle',
            fill: 'transparent',
            stroke: 'onTertiaryContainer',
            strokeWidth: 1,
            opacity: 0.35,
        },
        ringInner: {
            id: 'ringInner',
            type: 'shape',
            x: 22,
            y: 22,
            width: 136,
            height: 136,
            shapeType: 'circle',
            fill: 'transparent',
            stroke: 'onTertiaryContainer',
            strokeWidth: 1,
            opacity: 0.2,
        },
        dotLeft: {
            id: 'dotLeft',
            type: 'shape',
            x: 24,
            y: 136,
            width: 6,
            height: 6,
            shapeType: 'circle',
            fill: 'onTertiaryContainer',
            opacity: 0.7,
        },
        dotRight: {
            id: 'dotRight',
            type: 'shape',
            x: 150,
            y: 136,
            width: 6,
            height: 6,
            shapeType: 'circle',
            fill: 'onTertiaryContainer',
            opacity: 0.7,
        },
        centerIcon: {
            id: 'centerIcon',
            type: 'icon',
            x: 66,
            y: 66,
            width: 48,
            height: 48,
            name: 'star-four-points',
            color: 'tertiary',
            size: 48,
        },
        curvedText: {
            id: 'curvedText',
            type: 'curvedText',
            x: 5,
            y: 8,
            width: 170,
            height: 90,
            content: '• STAY POSITIVE • WORK HARD •',
            fontSize: 9,
            fontWeight: 'bold',
            color: 'onTertiaryContainer',
            curveType: 'arc',
            curveAmount: 100,
            startOffset: 50,
            letterSpacing: 0.6,
        },
    },
    componentOrder: ['bg', 'ringOuter', 'ringInner', 'dotLeft', 'dotRight', 'centerIcon', 'curvedText'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onTertiaryContainer',
        accent: 'tertiary',
        background: 'tertiaryContainer',
        onBackground: 'onTertiaryContainer',
    },
    dataBindings: [],
};

// ============================================
// Typography Poster (medium: 180×180)
// ============================================

export const typographyPoster: WidgetTemplate = {
    id: 'typography-poster',
    name: 'Type Poster',
    description: 'Expressive typography design',
    category: 'productivity',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'surface',
            cornerRadius: 0,
        },
        word1: {
            id: 'word1',
            type: 'text',
            x: 5,
            y: 20,
            width: 170,
            height: 40,
            content: 'CREATE',
            fontSize: 34,
            fontWeight: 'bold',
            color: 'onSurface',
            textAlign: 'center',
            letterSpacing: 3,
        },
        word2: {
            id: 'word2',
            type: 'text',
            x: 10,
            y: 65,
            width: 160,
            height: 30,
            content: 'YOUR',
            fontSize: 24,
            fontWeight: 'medium',
            color: 'tertiary',
            textAlign: 'center',
            letterSpacing: 6,
        },
        line: {
            id: 'line',
            type: 'shape',
            x: 70,
            y: 100,
            width: 40,
            height: 2,
            shapeType: 'rectangle',
            fill: 'tertiary',
        },
        word3: {
            id: 'word3',
            type: 'text',
            x: 10,
            y: 110,
            width: 160,
            height: 60,
            content: 'OWN\nREALITY',
            fontSize: 28,
            fontWeight: 'bold',
            color: 'primary',
            textAlign: 'center',
            lineHeight: 28,
        },
    },
    componentOrder: ['bg', 'word1', 'word2', 'line', 'word3'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'onSurface',
        accent: 'tertiary',
        background: 'surface',
        onBackground: 'onSurface',
    },
    dataBindings: [],
};

// ============================================
// Greeting Widget (medium: 180×180)
// ============================================

export const greetingWidget: WidgetTemplate = {
    id: 'greeting',
    name: 'Greeting',
    description: 'Personalized greeting message',
    category: 'productivity',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'secondaryContainer',
            cornerRadius: 32,
        },
        waveIcon: {
            id: 'waveIcon',
            type: 'icon',
            x: 66,
            y: 30,
            width: 48,
            height: 48,
            name: 'hand-wave',
            color: 'secondary',
            size: 48,
        },
        greeting: {
            id: 'greeting',
            type: 'text',
            x: 20,
            y: 95,
            width: 140,
            height: 24,
            content: '{device.greeting}!',
            fontSize: 18,
            fontWeight: 'semibold',
            color: 'onSecondaryContainer',
            textAlign: 'center',
        },
        subtext: {
            id: 'subtext',
            type: 'text',
            x: 20,
            y: 125,
            width: 140,
            height: 20,
            content: 'Ready to create?',
            fontSize: 14,
            fontWeight: 'normal',
            color: 'onSecondaryContainer',
            textAlign: 'center',
            opacity: 0.8,
        },
    },
    componentOrder: ['bg', 'waveIcon', 'greeting', 'subtext'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'secondary',
        secondary: 'onSecondaryContainer',
        accent: 'secondary',
        background: 'secondaryContainer',
        onBackground: 'onSecondaryContainer',
    },
    dataBindings: ['device.greeting'],
};

// Export all quote templates
export const quoteTemplates = [
    quoteMinimal,
    quoteBold,
    curvedQuote,
    typographyPoster,
    greetingWidget,
];

