/**
 * WidgetCraft - Utility Widget Templates
 * Battery, storage, and device info widgets
 *
 * COORDINATE SYSTEM: All components use top-left positioning.
 * (x, y) = top-left corner of the component bounding box.
 * Widget sizes: small=180×90, medium=180×180, large=360×180, extraLarge=360×360
 */

import { WidgetTemplate } from '../types';

// ============================================
// Battery Widget - Arc Style (small: 180×90)
// ============================================

export const batteryArc: WidgetTemplate = {
    id: 'battery-arc',
    name: 'Battery Arc',
    description: 'Circular battery indicator',
    category: 'utility',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 90,
            shapeType: 'squircle',
            fill: 'tertiaryContainer',
            cornerRadius: 24,
        },
        progress: {
            id: 'progress',
            type: 'progress',
            x: 15,
            y: 20,
            width: 50,
            height: 50,
            progressType: 'circle',
            value: 'battery.level',
            color: 'tertiary',
            backgroundColor: 'onTertiaryContainer',
            strokeWidth: 6,
            showLabel: false,
        },
        percentage: {
            id: 'percentage',
            type: 'text',
            x: 15,
            y: 33,
            width: 50,
            height: 24,
            content: '{battery.level}%',
            fontSize: 14,
            fontWeight: 'bold',
            color: 'onTertiaryContainer',
            textAlign: 'center',
            opacity: 0.9,
        },
        label: {
            id: 'label',
            type: 'text',
            x: 85,
            y: 28,
            width: 80,
            height: 14,
            content: 'BATTERY',
            fontSize: 10,
            fontWeight: 'semibold',
            color: 'tertiary',
            textAlign: 'center',
            letterSpacing: 1,
            opacity: 0.8,
        },
        status: {
            id: 'status',
            type: 'text',
            x: 85,
            y: 45,
            width: 80,
            height: 20,
            content: '{battery.level}%',
            fontSize: 18,
            fontWeight: 'bold',
            color: 'onTertiaryContainer',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'progress', 'percentage', 'label', 'status'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onTertiaryContainer',
        accent: 'tertiary',
        background: 'tertiaryContainer',
        onBackground: 'onTertiaryContainer',
    },
    dataBindings: ['battery.level', 'battery.isCharging'],
};

// ============================================
// Battery Widget - Pill Style (small: 180×90)
// ============================================

export const batteryPill: WidgetTemplate = {
    id: 'battery-pill',
    name: 'Battery Pill',
    description: 'Compact battery bar',
    category: 'utility',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 90,
            shapeType: 'squircle',
            fill: 'surfaceVariant',
            cornerRadius: 24,
        },
        icon: {
            id: 'icon',
            type: 'icon',
            x: 18,
            y: 33,
            width: 24,
            height: 24,
            name: 'battery-80',
            color: 'primary',
            size: 24,
        },
        progress: {
            id: 'progress',
            type: 'progress',
            x: 52,
            y: 38,
            width: 80,
            height: 14,
            progressType: 'bar',
            value: 'battery.level',
            color: 'primary',
            backgroundColor: 'surface',
            strokeWidth: 14,
        },
        percentage: {
            id: 'percentage',
            type: 'text',
            x: 138,
            y: 35,
            width: 40,
            height: 20,
            content: '{battery.level}%',
            fontSize: 13,
            fontWeight: 'bold',
            color: 'onSurfaceVariant',
            textAlign: 'left',
        },
    },
    componentOrder: ['bg', 'icon', 'progress', 'percentage'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'onSurfaceVariant',
        accent: 'primary',
        background: 'surfaceVariant',
        onBackground: 'onSurfaceVariant',
    },
    dataBindings: ['battery.level', 'battery.isCharging'],
};

// ============================================
// Device Info Widget (medium: 180×180)
// ============================================

export const deviceInfo: WidgetTemplate = {
    id: 'device-info',
    name: 'Device Info',
    description: 'Device name and storage',
    category: 'utility',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'surfaceVariant',
            cornerRadius: 32,
        },
        deviceIcon: {
            id: 'deviceIcon',
            type: 'icon',
            x: 66,
            y: 20,
            width: 48,
            height: 48,
            name: 'cellphone',
            color: 'onSurfaceVariant',
            size: 48,
        },
        deviceName: {
            id: 'deviceName',
            type: 'text',
            x: 20,
            y: 78,
            width: 140,
            height: 24,
            content: '{device.name}',
            fontSize: 18,
            fontWeight: 'semibold',
            color: 'onSurfaceVariant',
            textAlign: 'center',
            letterSpacing: 0.5,
        },
        storageBg: {
            id: 'storageBg',
            type: 'shape',
            x: 20,
            y: 115,
            width: 140,
            height: 40,
            shapeType: 'squircle',
            fill: 'surface',
            cornerRadius: 12,
            opacity: 0.5,
        },
        storageIcon: {
            id: 'storageIcon',
            type: 'icon',
            x: 30,
            y: 125,
            width: 20,
            height: 20,
            name: 'harddisk',
            color: 'onSurface',
            size: 20,
        },
        storageText: {
            id: 'storageText',
            type: 'text',
            x: 60,
            y: 126,
            width: 90,
            height: 18,
            content: '12 GB / 64 GB',
            fontSize: 12,
            fontWeight: 'medium',
            color: 'onSurface',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'deviceIcon', 'deviceName', 'storageBg', 'storageIcon', 'storageText'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'secondary',
        secondary: 'onSurfaceVariant',
        accent: 'secondary',
        background: 'surfaceVariant',
        onBackground: 'onSurfaceVariant',
    },
    dataBindings: ['device.name'],
};

// ============================================
// Battery Ring (small: 180×90)
// ============================================

export const batteryRing: WidgetTemplate = {
    id: 'battery-ring',
    name: 'Battery Ring',
    description: 'Minimalist ring battery',
    category: 'utility',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 45,
            y: 0,
            width: 90,
            height: 90,
            shapeType: 'circle',
            fill: 'surface',
        },
        progress: {
            id: 'progress',
            type: 'progress',
            x: 50,
            y: 5,
            width: 80,
            height: 80,
            progressType: 'circle',
            value: 'battery.level',
            color: 'primary',
            backgroundColor: 'surfaceVariant',
            strokeWidth: 8,
            showLabel: false,
        },
        percentage: {
            id: 'percentage',
            type: 'text',
            x: 50,
            y: 35,
            width: 80,
            height: 20,
            content: '{battery.level}%',
            fontSize: 16,
            fontWeight: 'bold',
            color: 'onSurface',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'progress', 'percentage'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'surface',
        onBackground: 'onSurface',
    },
    dataBindings: ['battery.level'],
};

// ============================================
// System Dashboard (medium: 180×180)
// ============================================

export const systemDashboard: WidgetTemplate = {
    id: 'system-dashboard',
    name: 'System Dashboard',
    description: 'Time, date, and system status',
    category: 'utility',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'inverseSurface',
            cornerRadius: 28,
        },
        // --- Top: Time ---
        timeLabel: {
            id: 'timeLabel',
            type: 'text',
            x: 20,
            y: 18,
            width: 60,
            height: 14,
            content: 'TIME',
            fontSize: 10,
            fontWeight: 'bold',
            color: 'inverseOnSurface',
            opacity: 0.5,
            letterSpacing: 1,
        },
        time: {
            id: 'time',
            type: 'text',
            x: 20,
            y: 35,
            width: 140,
            height: 34,
            content: '{time.formatted24}',
            fontSize: 28,
            fontWeight: 'bold',
            color: 'inverseOnSurface',
        },

        // --- Middle: Date ---
        dateLabel: {
            id: 'dateLabel',
            type: 'text',
            x: 20,
            y: 78,
            width: 60,
            height: 14,
            content: 'DATE',
            fontSize: 10,
            fontWeight: 'bold',
            color: 'inverseOnSurface',
            opacity: 0.5,
            letterSpacing: 1,
        },
        dateDay: {
            id: 'dateDay',
            type: 'text',
            x: 20,
            y: 95,
            width: 140,
            height: 22,
            content: '{date.dayShort}, {date.monthShort} {date.day}',
            fontSize: 16,
            fontWeight: 'medium',
            color: 'inverseOnSurface',
        },

        // --- Divider ---
        divider: {
            id: 'divider',
            type: 'shape',
            x: 20,
            y: 128,
            width: 140,
            height: 1,
            shapeType: 'rectangle',
            fill: 'inverseOnSurface',
            fillOpacity: 0.2,
        },

        // --- Bottom: Battery ---
        batteryIcon: {
            id: 'batteryIcon',
            type: 'icon',
            x: 20,
            y: 142,
            width: 24,
            height: 24,
            name: 'battery',
            color: 'inversePrimary',
            size: 24,
        },
        batteryLevel: {
            id: 'batteryLevel',
            type: 'text',
            x: 50,
            y: 145,
            width: 60,
            height: 20,
            content: '{battery.level}%',
            fontSize: 16,
            fontWeight: 'bold',
            color: 'inversePrimary',
        },
        chargingIcon: {
            id: 'chargingIcon',
            type: 'icon',
            x: 115,
            y: 146,
            width: 16,
            height: 16,
            name: 'lightning-bolt',
            color: 'inversePrimary',
            size: 16,
        },
    },
    componentOrder: ['bg', 'timeLabel', 'time', 'dateLabel', 'dateDay', 'divider', 'batteryIcon', 'batteryLevel', 'chargingIcon'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'inversePrimary',
        secondary: 'inverseOnSurface',
        accent: 'tertiary',
        background: 'inverseSurface',
        onBackground: 'inverseOnSurface',
    },
    dataBindings: ['time.formatted24', 'date.dayShort', 'battery.level'],
};

// Export all utility templates
export const utilityTemplates = [
    batteryArc,
    batteryPill,
    deviceInfo,
    batteryRing,
    systemDashboard,
];
