/**
 * WidgetCraft - Weather Widget Templates
 * M3 Expressive weather designs with dynamic colors
 *
 * COORDINATE SYSTEM: All components use top-left positioning.
 * (x, y) = top-left corner of the component bounding box.
 * Widget sizes: small=180×90, medium=180×180, large=360×180, extraLarge=360×360
 */

import { WidgetTemplate } from '../types';

// ============================================
// Weather Compact (small: 180×90)
// ============================================

export const weatherCompact: WidgetTemplate = {
    id: 'weather-compact',
    name: 'Weather Compact',
    description: 'Simple temperature and condition',
    category: 'weather',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 90,
            shapeType: 'squircle',
            fill: 'primaryContainer',
            cornerRadius: 24,
        },
        icon: {
            id: 'icon',
            type: 'icon',
            x: 15,
            y: 25,
            width: 40,
            height: 40,
            name: 'weather-partly-cloudy',
            color: 'primary',
            size: 40,
        },
        temp: {
            id: 'temp',
            type: 'text',
            x: 70,
            y: 15,
            width: 100,
            height: 40,
            content: '{weather.temp}°',
            fontSize: 32,
            fontWeight: 'bold',
            color: 'onPrimaryContainer',
            textAlign: 'center',
        },
        condition: {
            id: 'condition',
            type: 'text',
            x: 70,
            y: 55,
            width: 100,
            height: 20,
            content: '{weather.condition}',
            fontSize: 12,
            fontWeight: 'normal',
            color: 'onPrimaryContainer',
            textAlign: 'center',
            opacity: 0.8,
        },
    },
    componentOrder: ['bg', 'icon', 'temp', 'condition'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'primaryContainer',
        onBackground: 'onPrimaryContainer',
    },
    dataBindings: ['weather.temp', 'weather.condition', 'weather.icon'],
};

// ============================================
// Weather Full (medium: 180×180)
// ============================================

export const weatherFull: WidgetTemplate = {
    id: 'weather-full',
    name: 'Weather Full',
    description: 'Complete weather with high/low',
    category: 'weather',
    size: 'medium',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 180,
            shapeType: 'squircle',
            fill: 'secondaryContainer',
            cornerRadius: 32,
        },
        iconBg: {
            id: 'iconBg',
            type: 'shape',
            x: 55,
            y: 16,
            width: 70,
            height: 70,
            shapeType: 'circle',
            fill: 'secondary',
            fillOpacity: 0.15,
        },
        icon: {
            id: 'icon',
            type: 'icon',
            x: 69,
            y: 30,
            width: 42,
            height: 42,
            name: 'weather-sunny',
            color: 'secondary',
            size: 42,
        },
        temp: {
            id: 'temp',
            type: 'text',
            x: 40,
            y: 92,
            width: 100,
            height: 40,
            content: '{weather.temp}°',
            fontSize: 36,
            fontWeight: 'bold',
            color: 'onSecondaryContainer',
            textAlign: 'center',
        },
        condition: {
            id: 'condition',
            type: 'text',
            x: 20,
            y: 135,
            width: 140,
            height: 20,
            content: '{weather.condition}',
            fontSize: 14,
            fontWeight: 'medium',
            color: 'onSecondaryContainer',
            textAlign: 'center',
            letterSpacing: 0.5,
        },
        highLow: {
            id: 'highLow',
            type: 'text',
            x: 20,
            y: 157,
            width: 140,
            height: 16,
            content: 'H: {weather.high}°  L: {weather.low}°',
            fontSize: 12,
            fontWeight: 'normal',
            color: 'onSecondaryContainer',
            textAlign: 'center',
            opacity: 0.7,
        },
    },
    componentOrder: ['bg', 'iconBg', 'icon', 'temp', 'condition', 'highLow'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'secondary',
        secondary: 'onSecondaryContainer',
        accent: 'secondary',
        background: 'secondaryContainer',
        onBackground: 'onSecondaryContainer',
    },
    dataBindings: ['weather.temp', 'weather.condition', 'weather.high', 'weather.low', 'weather.icon'],
};

// ============================================
// Weather with Time (large: 360×180)
// ============================================

export const weatherWithTime: WidgetTemplate = {
    id: 'weather-time',
    name: 'Weather + Time',
    description: 'Weather alongside current time',
    category: 'weather',
    size: 'large',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 360,
            height: 180,
            shapeType: 'squircle',
            fill: 'primaryContainer',
            cornerRadius: 32,
        },
        // Left side - Time
        time: {
            id: 'time',
            type: 'text',
            x: 20,
            y: 45,
            width: 150,
            height: 50,
            content: '{time.formatted24}',
            fontSize: 44,
            fontWeight: 'bold',
            color: 'onPrimaryContainer',
            textAlign: 'center',
            letterSpacing: -1,
        },
        date: {
            id: 'date',
            type: 'text',
            x: 20,
            y: 105,
            width: 150,
            height: 24,
            content: '{date.dayName}, {date.monthShort} {date.day}',
            fontSize: 14,
            fontWeight: 'medium',
            color: 'onPrimaryContainer',
            textAlign: 'center',
            opacity: 0.8,
        },
        // Divider
        divider: {
            id: 'divider',
            type: 'shape',
            x: 179,
            y: 30,
            width: 2,
            height: 120,
            shapeType: 'rectangle',
            fill: 'onPrimaryContainer',
            fillOpacity: 0.1,
            cornerRadius: 1,
        },
        // Right side - Weather
        weatherIcon: {
            id: 'weatherIcon',
            type: 'icon',
            x: 200,
            y: 40,
            width: 48,
            height: 48,
            name: 'weather-cloudy',
            color: 'primary',
            size: 48,
        },
        weatherTemp: {
            id: 'weatherTemp',
            type: 'text',
            x: 260,
            y: 45,
            width: 80,
            height: 42,
            content: '{weather.temp}°',
            fontSize: 36,
            fontWeight: 'bold',
            color: 'onPrimaryContainer',
            textAlign: 'center',
        },
        weatherCondition: {
            id: 'weatherCondition',
            type: 'text',
            x: 200,
            y: 110,
            width: 140,
            height: 20,
            content: '{weather.condition}',
            fontSize: 14,
            fontWeight: 'medium',
            color: 'onPrimaryContainer',
            textAlign: 'center',
            opacity: 0.8,
        },
    },
    componentOrder: ['bg', 'time', 'date', 'divider', 'weatherIcon', 'weatherTemp', 'weatherCondition'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'primaryContainer',
        onBackground: 'onPrimaryContainer',
    },
    dataBindings: [
        'time.formatted24', 'date.dayName', 'date.monthShort', 'date.day',
        'weather.temp', 'weather.condition', 'weather.icon',
    ],
};

// ============================================
// Weather Card (small: 180×90)
// ============================================

export const weatherCard: WidgetTemplate = {
    id: 'weather-card',
    name: 'Weather Card',
    description: 'Pill-shaped modern weather card',
    category: 'weather',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 0,
            width: 180,
            height: 90,
            shapeType: 'squircle',
            fill: 'tertiaryContainer',
            cornerRadius: 45,
        },
        iconBg: {
            id: 'iconBg',
            type: 'shape',
            x: 15,
            y: 15,
            width: 60,
            height: 60,
            shapeType: 'circle',
            fill: 'tertiary',
            fillOpacity: 1,
        },
        icon: {
            id: 'icon',
            type: 'icon',
            x: 25,
            y: 25,
            width: 40,
            height: 40,
            name: 'weather-partly-cloudy',
            color: 'onTertiary',
            size: 40,
        },
        temp: {
            id: 'temp',
            type: 'text',
            x: 85,
            y: 15,
            width: 85,
            height: 36,
            content: '{weather.temp}°',
            fontSize: 34,
            fontWeight: 'bold',
            color: 'onTertiaryContainer',
            textAlign: 'left',
            letterSpacing: -1,
        },
        condition: {
            id: 'condition',
            type: 'text',
            x: 85,
            y: 55,
            width: 85,
            height: 18,
            content: '{weather.condition}',
            fontSize: 12,
            fontWeight: 'medium',
            color: 'onTertiaryContainer',
            textAlign: 'left',
            opacity: 0.7,
        },
    },
    componentOrder: ['bg', 'iconBg', 'icon', 'temp', 'condition'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'tertiary',
        secondary: 'onTertiaryContainer',
        accent: 'tertiary',
        background: 'tertiaryContainer',
        onBackground: 'onTertiaryContainer',
    },
    dataBindings: ['weather.temp', 'weather.condition', 'weather.icon'],
};

// ============================================
// Forecast Strip (small: 180×90)
// ============================================

export const forecastStrip: WidgetTemplate = {
    id: 'forecast-strip',
    name: 'Forecast Strip',
    description: 'Minimalist horizontal forecast',
    category: 'weather',
    size: 'small',
    components: {
        bg: {
            id: 'bg',
            type: 'shape',
            x: 0,
            y: 15,
            width: 180,
            height: 60,
            shapeType: 'squircle',
            fill: 'surface',
            cornerRadius: 16,
        },
        // Day
        day: {
            id: 'day',
            type: 'text',
            x: 5,
            y: 30,
            width: 50,
            height: 22,
            content: '{date.dayShort}',
            fontSize: 16,
            fontWeight: 'bold',
            color: 'onSurface',
            textAlign: 'center',
        },
        // Divider 1
        div1: {
            id: 'div1',
            type: 'shape',
            x: 60,
            y: 25,
            width: 1,
            height: 40,
            shapeType: 'rectangle',
            fill: 'outline',
            fillOpacity: 0.2,
        },
        // Icon
        icon: {
            id: 'icon',
            type: 'icon',
            x: 72,
            y: 29,
            width: 32,
            height: 32,
            name: 'weather-sunny',
            color: 'primary',
            size: 32,
        },
        // Divider 2
        div2: {
            id: 'div2',
            type: 'shape',
            x: 115,
            y: 25,
            width: 1,
            height: 40,
            shapeType: 'rectangle',
            fill: 'outline',
            fillOpacity: 0.2,
        },
        // Temp
        temp: {
            id: 'temp',
            type: 'text',
            x: 125,
            y: 30,
            width: 50,
            height: 22,
            content: '{weather.temp}°',
            fontSize: 18,
            fontWeight: 'bold',
            color: 'onSurface',
            textAlign: 'center',
        },
    },
    componentOrder: ['bg', 'day', 'div1', 'icon', 'div2', 'temp'],
    backgroundColor: 'transparent',
    colorScheme: {
        primary: 'primary',
        secondary: 'secondary',
        accent: 'tertiary',
        background: 'surface',
        onBackground: 'onSurface',
    },
    dataBindings: ['date.dayShort', 'weather.icon', 'weather.temp'],
};

// Export all weather templates
export const weatherTemplates = [
    weatherCompact,
    weatherFull,
    weatherWithTime,
    weatherCard,
    forecastStrip,
];
